### ISSUE TITLE
express cannot get segment in sub file

### ISSUE THREAD

**Issue by Mangosteen-Yang** [aws/aws-xray-sdk-node#158] opened 2019-07-26 00:22 UTC
Everything works well in app.js alone
However, If I call 

api/company.js
```
const AWSXRay = require('aws-xray-sdk');
AWSXRay.getSegment();
```
In a sub file (route redirected file) between openSegment() and closeSegment() I will get segment not found error.

app.js
```
const AWSXRay = require('aws-xray-sdk');
const company = require('../api/company');
app.use(AWSXRay.express.openSegment('defaultName'));
router
  .route('/companies')
  .get(company.companyGetAllDetail);
app.use(AWSXRay.express.closeSegment()); 
```

I assume segment should always available between open and close, right?

**Comment by awssandra** [comment] 2019-07-26 17:15
Hi Mangosteen-Yang,

It should be, but it needs to be on the request codepath. You'll have to use AWSXRay.getSegment() in the scope of the actual routing function(s), not in the module scope.

**Comment by Mangosteen-Yang** [comment] 2019-07-29 00:09
@awssandra Thanks for your reply.
I don't understand well. Can you tell me more detail about how to use AWSXRay.getSegment() in my compnay.js file?
I need to track subsegment in this file.

**Comment by awssandra** [comment] 2019-07-29 16:48
Hi Mangosteen-Yang,

Segments are created dynamically when a request is processed by the Express middleware. Thus, you can only use AWSXRay.getSegment() within the request path (as the segment is in scope). You cannot track this at the file level.

You'll have to add AWSXRay.getSegment() into the company.companyGetAllDetail function.

**Comment by Mangosteen-Yang** [comment] 2019-07-30 00:22
@awssandra Thanks. I got it.
It works but really annoying especially when my function is deep(comparing with app.js). I have to pass segment to many levels down.

**Comment by awssandra** [comment] 2019-07-31 15:34
Hi Mangosteen-Yang,

If you're running in automatic mode, you can simply use AWSXRay.getSegment() anywhere you need it - you don't need to pass the segment returned around. If you are in manual mode, it will be on the request object.

See example code here: 

https://github.com/aws/aws-xray-sdk-node/tree/master/packages/core#automatic-mode-examples
https://github.com/aws/aws-xray-sdk-node/tree/master/packages/core#manual-mode-examples

**Comment by Mangosteen-Yang** [comment] 2019-08-01 00:54
@awssandra Thanks. I created a clean environment with my example file, which works well.
The problem with my production code is it seems there an error to use this package after passport middleware.

I will find more details.

**Comment by Mangosteen-Yang** [comment] 2019-08-01 05:18
I figured it out.

If you are using passport with BearerStrategy as middleware. The example code

```
passport.use(new BearerStrategy(
  function(token, done) {
    User.findOne({ token: token }, function (err, user) {
      if (err) { return done(err); }
      if (!user) { return done(null, false); }
      return done(null, user, { scope: 'all' });
    });
  }
));
```

will cause segment not found in the router.

My solution is to rewrite the code with promise way like: 

```
    User.findOne({ token })
      .then((user) => {
        if (!user) { return done(null, false); }
        return done(null, user);
      })
      .catch(err => done(err));
  }
```

I did not dig deep to find the reason. If anyone can find the reason I will be appreciated.

**Comment by willarmiros** [comment] 2019-09-19 17:46
Although I would likely need more information to find the root cause, it's possible segment not found was being thrown because of the middleware using a different thread and causing issues with the context and/or `cls`. I'll close this for now, but please reopen if you have more questions!

**Closed by willarmiros** 2019-09-19 17:46 UTC
