### ISSUE TITLE
Capturing DynamoDB Client in TypeScript

### ISSUE THREAD

**Issue by luketn** [aws/aws-xray-sdk-node#304] opened 2020-06-09 11:35 UTC
I've had an exception attempting to capture the DynamoDB client using the code:
```
import {captureAWSClient} from "aws-xray-sdk-core";

const dynamoDb = captureAWSClient(new DynamoDB.DocumentClient());
```
(which seems like the correct way to do this)

Error: "TypeError: service.customizeRequests is not a function"

As a workaround, I used this:
```
import AWS from "aws-sdk";
import {captureAWS} from "aws-xray-sdk-core";

const aws = captureAWS(AWS);
const dynamoDb = new aws.DynamoDB.DocumentClient();
```
Which works but seems like a cludge.

**Comment by willarmiros** [comment] 2020-06-09 15:49
Hi @luketn, 
This issue has been reported in #23, which includes another workaround which doesn't use `captureAWS()`. I'd recommend you check that out. To summarize though, this doesn't work because the `documentClient` is different from other AWS clients, so our patcher doesn't work the same way. 

One thing worth noting is that V3 of the AWS SDK for JS is around the corner, and hopefully they will standardize the way `DocumentClient` is created so it can be captured like normal. [This](https://github.com/aws/aws-sdk-js-v3/issues/944#issuecomment-630036707) is the latest update (or lack thereof) I could find, but I have a feeling it will be much more captureable once it is released in v3. Anyway, I'm going to close this as a dupe of #23, please follow up there with further DocumentClient issues :)

**Closed by willarmiros** 2020-06-09 15:49 UTC

**Comment by brucemackenzie** [comment] 2020-10-03 16:40
We use aws as a namespace as well so we ended up with this hack:

```
import * as AWSType from "aws-sdk";				// use only for typing
import { captureAWS } from "aws-xray-sdk-core";
const AWS = captureAWS(AWSType);				// instrumented for logic
```
then we can use one for typing and one for logic:
```
let dynamoDB: AWSType.DynamoDB = new AWS.DynamoDB();
```

**Comment by luisfarzati** [comment] 2020-12-09 20:24
I'm trying to use XRay with the SDK v3 without any luck. I cannot find any examples either -- is v3 supported for XRay?

```
import { SendMessageCommand, SQSClient } from '@aws-sdk/client-sqs';
import { captureAWSClient } from 'aws-xray-sdk-core';
const client = captureAWSClient(new SQSClient({}));
```

**Comment by srprash** [comment] 2020-12-09 21:19
Hi @luisfarzati We are working towards adding the AWS SDK v3 support to X-Ray. This is the related [issue](https://github.com/aws/aws-xray-sdk-node/issues/294) and corresponding [PR](https://github.com/aws/aws-xray-sdk-node/pull/298) under review.

**Comment by dlaudams** [comment] 2022-06-24 06:05
@luisfarzati 

> I'm trying to use XRay with the SDK v3 without any luck. I cannot find any examples either -- is v3 supported for XRay?
> 
> ```
> import { SendMessageCommand, SQSClient } from '@aws-sdk/client-sqs';
> import { captureAWSClient } from 'aws-xray-sdk-core';
> const client = captureAWSClient(new SQSClient({}));
> ```

It's supported now, but you need a different function `captureAWSv3Client` to wrap the client. This is not well documented.

https://github.com/aws/aws-xray-sdk-node/issues/294

Try:

```
import { SendMessageCommand, SQSClient } from '@aws-sdk/client-sqs';
import { captureAWSv3Client } from 'aws-xray-sdk-core';
const client = captureAWSv3Client(new SQSClient({}));
```

**Comment by Sonumajuru** [comment] 2024-04-10 12:05
Hi I know issue might be closed but how can I trace using Xray for V3 client 

const { captureAWSv3Client } = require('aws-xray-sdk-core')
const { DynamoDBClient } = require('@aws-sdk/client-dynamodb')
const { DynamoDBDocumentClient, GetCommand } = require('@aws-sdk/lib-dynamodb')

then

 const dynamodb = captureAWSv3Client(new DynamoDBClient(this.dynamoConfig))
    this.docClient = DynamoDBDocumentClient.from(dynamodb)

returns 
"error",
    "msg": "Missing AWS Lambda trace data for X-Ray. Ensure Active Tracing is enabled and no subsegments are created outside the function handler.",

There is no segments created out of this scope.
Is Xray still not supported with V3?
