### ISSUE TITLE
Unable to connect to mysql after upgrading to 2.3.3

### ISSUE THREAD

**Issue by rrosenblum** [aws/aws-xray-sdk-node#136] opened 2019-05-08 12:47 UTC
After upgrading from version 2.2.0 to 2.3.3, I am unable to connect to mysql. I believe this is related to #98. There isn't much of an actual error being produced that I can see. The lambda just winds up timing out without ever actually connecting to mysql. I have tried increasing the timeout. I think this might be related to #98.

I have tried 2 different ways to capture mysql.

```js
const AWSXRay = require('aws-xray-sdk-core');    
const captureMySQL = require('aws-xray-sdk-mysql');    
const mysql = captureMySQL(require('mysql'));    
                                         
const pool = mysql.createPool({    
  host: process.env.DB_PRIMARY_ENDPOINT,    
  database: process.env.DB_NAME,    
  port: process.env.DB_PORT,    
  user: process.env.DB_USERNAME,    
  password: process.env.DB_PASSWORD    
});

module.exports.handler = async (event) => {
  pool.query
}
```
    
```js
const mysql = require('aws-xray-sdk').captureMySQL(require('mysql'));    
    
const pool = mysql.createPool({    
  host: process.env.DB_PRIMARY_ENDPOINT,    
  database: process.env.DB_NAME,    
  port: process.env.DB_PORT,    
  user: process.env.DB_USERNAME,    
  password: process.env.DB_PASSWORD    
});

module.exports.handler = async (event) => {
  pool.query
}
```

**Comment by awssandra** [comment] 2019-05-08 17:30
Hi rrosenblum,

Sorry for the issues. We'll do some testing on our end to see what the issue is. I think it's a fair call that the mysql2 changes may have broken the mysql patch functionality.

**Comment by M-TGH** [comment] 2019-05-08 22:09
Hey,

Thanks for the report. My apologies for any inconveniences. I didn't have too much time so far to look into it, but I was able to reproduce it. For now it should be alright to (temporarily) remove the parts that patch a Pool it's getConnection function. 

So far it looked like it's somewhere down that line that something was hitting a snag, maybe because the MySQL package internally uses getConnection on the Pool when using Pool.query. Unfortunately I couldn't yet figure out the full problem, but I'll try looking into it more as soon as I have the time. 

Suppose it might be interesting to see if this can be replicated with a test which stubs/simulates a Pool's query function.

Let me know if I can be of any more help.

**Comment by M-TGH** [comment] 2019-05-09 06:36
After looking into it further, Pool.query creates a Query instance and a connection and then calls the connection.query function with only the Query instance as argument. This falls into this case, from further up in query: https://github.com/mysqljs/mysql/blob/99d6f78ba00f926de162dbef42865029b6e8ec39/lib/Connection.js#L26

It's currently going into this if statement: https://github.com/aws/aws-xray-sdk-node/blob/ad817e5ccfbb803ec4140cd8a457be579ea3cc1c/packages/mysql/lib/mysql_p.js#L142
Which then splits up the Query instance that was passed through and currently makes it so that a new one is created by calling Connection.query with its sql and values, thereby losing the original Query instances EventEmitter.

**Comment by yvele** [comment] 2019-05-20 10:08
I confirm the bug with `2.3.3` and `2.3.0`

**Comment by willarmiros** [comment] 2019-10-03 22:53
Closing since it was fixed in PR.

**Closed by willarmiros** 2019-10-03 22:53 UTC
