### ISSUE TITLE
Captured internal error during running

### ISSUE THREAD

**Issue by Mangosteen-Yang** [aws/aws-xray-sdk-node#293] opened 2020-05-12 04:32 UTC
We are using sentry to catch exceptions and today I get this during our application running:

```
TypeError: Cannot read property 'forEach' of undefined
  File "/var/app/current/node_modules/aws-xray-sdk-core/lib/middleware/sampling/service_connector.js", line 147, col 8, in assembleTargets
    docs.forEach(function(doc) {
  File "/var/app/current/node_modules/aws-xray-sdk-core/lib/middleware/sampling/service_connector.js", line 82, col 30, in IncomingMessage.<anonymous>
    var targetsMapping = assembleTargets(dataObj);
  File "events.js", line 322, col 22, in IncomingMessage.emit
  File "domain.js", line 505, col 15, in IncomingMessage.EventEmitter.emit
  File "_stream_readable.js", line 1187, col 12, in endReadableNT
  File "internal/process/task_queues.js", line 84, col 21, in processTicksAndRejections
```

**Comment by willarmiros** [comment] 2020-05-12 14:13
Hi @Mangosteen-Yang, 
I believe this is a duplicate of #285. We've released a fix in v3.0.1, please upgrade and let me know if that fixes it!

**Comment by willarmiros** [comment] 2020-05-12 16:33
Would you mind also posting your application logs to help us see if there are any clues to the source of this error?

**Comment by Mangosteen-Yang** [comment] 2020-05-14 05:00
@willarmiros I monitored for two days. It seems no error after upgrading to v3.0.1

**Comment by willarmiros** [comment] 2020-05-15 18:56
Good to hear, I'll close this now.

**Closed by willarmiros** 2020-05-15 18:56 UTC
