### ISSUE TITLE
package is un-necessarily large

### ISSUE THREAD

**Issue by joshuawinsor** [aws/aws-xray-sdk-node#186] opened 2019-09-16 21:08 UTC
aws-xray-sdk@2.3.6 when installed from NPM makes the simplest lambda function 9 megs, this means that it can not be edited in the lambda console.  
low hanging fruit to fix this is to remove lodash (while it appears that an effort has been made to that effect, it is still a dependency when installed via npm as of version 2.3.6), and to make AWS-SDK a devDependency or peerDependency as it is already a layer in AWS Lambda.

**Comment by hotgazpacho** [comment] 2019-09-22 15:55
Totally agree! `aws-sdk` is natively available in a Lambda environment, so `aws-sdk` should be a `peerDependency`, not a `dependency`

**Comment by willarmiros** [comment] 2019-09-23 18:56
Thank you for both your valid points and the PR you submitted for this issue. The X-Ray SDK is meant to be used in any environment, so even though the AWS SDK is available in Lambda it may not be for other use cases. That being said there are active discussions for removing `aws-sdk` as a dependency and we will update you all soon on that.

The removal of Lodash as a dependency has been merged into Github and will be included in the next release of the SDK on NPM. Furthermore, #190 has been created which will remove `winston`, another package too large given our underutilization of it. Hopefully this answers some concerns about the package size going forward.

**Comment by willarmiros** [comment] 2019-10-25 22:24
Closing since this is a duplicate of #113

**Closed by willarmiros** 2019-10-25 22:24 UTC
