### ISSUE TITLE
Using setContextMissingStrategy is cumbersome.

### ISSUE THREAD

**Issue by swisener** [aws/aws-xray-sdk-node#302] opened 2020-06-04 16:44 UTC
The SDK will not override the context missing strategy if the environment variable AWS_XRAY_CONTEXT_MISSING is set; however, AWS_XRAY_CONTEXT_MISSING is set by the Lambda runtime to LOG_ERROR by default (see https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html). In order to actually override the value, you need to unset the value before calling setContextMissingStrategy, which is cumbersome.

**Comment by willarmiros** [comment] 2020-06-09 15:28
Hi @swisener,
Thank you for raising this issue. I agree that it's unwieldy to modify the context missing strategy in Lambda currently. However changing the behavior to have the API override the environment variable would constitute a breaking change and only be possible in the next major version bump. We'd probably only want to allow this behavior in Lambda, where the runtime sets the environment variable, since in other cases we should stay consistent about environment variables' priority over programmatic settings.

**Comment by kdybicz** [comment] 2020-10-02 14:13
I'm trying to go with:
```
delete process.env.AWS_XRAY_CONTEXT_MISSING;
AWSXRay.setContextMissingStrategy((msg) => { console.log(msg); });
```
but even though I can confirm with `console.log(JSON.stringify(process.env));` that `AWS_XRAY_CONTEXT_MISSING` was unset, I'm still getting the default `LOG_ERROR` behaviour in my Lambda...

**Comment by willarmiros** [comment] 2020-10-12 22:39
Hi @kdybicz,
Thanks for the deep dive and happy you ended up finding the workaround. I'd agree that, if the environment variable is unset, `setContextMissingStrategy` should behave as expected. I'd be open to a PR to correct that behavior if you made one, otherwise I'll try to make this change if I have some time.

**Comment by kdybicz** [comment] 2020-10-13 12:02
Hi @willarmiros 

I've looked at a potential ways of fixing that problem, but I found that there are two mutual exclusive (for simple approach) test cases:
```
ContextUtils
    #setContextMissingStrategy
        should ignore the configuration change if process.env.AWS_XRAY_CONTEXT_MISSING is set:
```
```
ContextUtils
    init
        should set the contextMissingStrategy to the process.env.AWS_XRAY_CONTEXT_MISSING strategy if present:
```

So I'm trying to figure out what would be the expected Use Cases:
1. When: `process.env.AWS_XRAY_CONTEXT_MISSING` is missing on initialisation
Then:
```
  contextUtils.contextMissingStrategy.contextMissing = contextUtils.CONTEXT_MISSING_STRATEGY.RUNTIME_ERROR.contextMissing;
  logger.getLogger().debug('Using default context missing strategy: RUNTIME_ERROR');
```
2. When: `process.env.AWS_XRAY_CONTEXT_MISSING` is present on initialisation
Then: `contextUtils.setContextMissingStrategy(process.env.AWS_XRAY_CONTEXT_MISSING);`
3. When: `setContextMissingStrategy` called after initialisation
a. Take `process.env.AWS_XRAY_CONTEXT_MISSING` into consideration and... do what?
b. Ignore whatever is in `process.env.AWS_XRAY_CONTEXT_MISSING` and always allow `setContextMissingStrategy` to change `contextMissing` behaviour. Could this have any unexpected side effects?
4. Anything beside that?

**Comment by willarmiros** [comment] 2020-10-13 14:55
Hi @kdybicz, you're right on all counts for the expected behavior. With respect to point 3: I don't think option B should be the case, we should never override the Context Missing Strategy (CMS) set by the environment variable if it's present. The way we implement that right now is we set a [contextOverride flag](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/context_utils.js#L201) if an environment variable is present at initialization and don't check for the environment variable ever again, we just treat the CMS as immutable.

That is a common pattern across all of our SDKs, where we read environment variables at startup and give them the highest order of priority for configuring the SDK. We don't expect environment variables to change at runtime because doing something like `delete process.env.MY_VARIABLE` *doesn't actually unset the variable in your environment, it just deletes it from your program's memory.* So I'm actually somewhat hesitant to change this behavior since it is correct in theory. 

So the fix actually could be adding a new strategy to [this enum](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/context_utils.js#L18) called, `CUSTOM`, which would allow the context missing strategy to be overridden by `setContextMissingStrategy`. Then you could set the `AWS_XRAY_CONTEXT_MISSING` environment variable to `CUSTOM` in your Lambda console and that should override the `LOG_ERROR` strategy put in place by Lambda, and you'd be able to call `setContextMissingStrategy` as expected.

**Comment by kdybicz** [comment] 2020-10-13 15:19
Hi @willarmiros, do you think that in such case we could add ie. `LOG_WARN` and `MUTE` strategy to mentioned enum? `MUTE` for people who don't need/want to care about missing context and `LOG_WARN` to log all of the messages as WARN and make them not count as errors in alerts people could have configured?

**Comment by willarmiros** [comment] 2020-10-20 14:36
@kdybicz @swisener I've also realized that, in the Lambda console, you can simply set the `AWS_XRAY_CONTEXT_MISSING` environment variable to nothing, and it will overwrite the default LOG_ERROR setting. From there, you can use `AWSXRay.setContextMissingStrategy()` as expected. Not sure why I didn't think of this earlier instead of proposing a new value for the env var, but I'm going to close this out since I think this workaround is a fairly straightforward way to customize the context missing strategy in Lambda.

**Closed by willarmiros** 2020-10-20 14:36 UTC
Labels: discussion, enhancement

**Comment by kdybicz** [comment] 2020-10-20 14:48
All good, though... this confusion would probably suggest that there are some lacks in documentation somewhere. For me too it wasn't clear at the beginning for to setup things properly for Lambda! :)

**Comment by swisener** [comment] 2020-10-20 14:56
> @kdybicz @swisener I've also realized that, in the Lambda console, you can simply set the `AWS_XRAY_CONTEXT_MISSING` environment variable to nothing, and it will overwrite the default LOG_ERROR setting. From there, you can use `AWSXRay.setContextMissingStrategy()` as expected. Not sure why I didn't think of this earlier instead of proposing a new value for the env var, but I'm going to close this out since I think this workaround is a fairly straightforward way to customize the context missing strategy in Lambda.

Having to override the environment variable to an empty string in order to use a custom function is the "cumbersome" part of the issue. First, you have to figure out that the node lambda runtime sets a default value for this environment variable, then you have to figure out how to get the XRay SDK to actually use your custom function, since it won't do it by default.

**Comment by willarmiros** [comment] 2020-10-20 15:24
^ I've submitted this pull request to the official Lambda documentation to describe this process, hopefully it will resolve some confusion for future customers:
