### ISSUE TITLE
Support for tracing requests in X-Ray SDK for Node.js with sequelize and mysql2

### ISSUE THREAD

**Issue by eistrati** [aws/aws-xray-sdk-node#275] opened 2020-04-09 23:38 UTC
We have tried and failed to replicate the workaround for sequelize and mysql2, similar to the one provided for sequelize and postgresql described in this issue: https://github.com/aws/aws-xray-sdk-node/issues/271

Can you please help with providing support for sequelize and mysql2? Any workarounds available as of today?

**Comment by willarmiros** [comment] 2020-04-10 13:43
Hi @eistrati, 
Thanks for raising this issue. At the moment this SDK does not support automatic tracing of the `mysql2` library, we only support `mysql` and `postgres`. We are always open to pull requests.

As a workaround, you can manually create a subsegment around your `mysql2` query and add your sqlData yourself. See this [documentation](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html#api-segmentdocuments-sql) for a list of whitelisted fields in the `sql` field of subsegments.

```js
const sqlObj = {
  database_type: 'MySQL',
  database_version: '1.0.0'
};

var sub = AWSXRay.getSegment().addNewSubsegment('mysql2');

// Make query

sub.addSqlData(sqlObj);
sub.close();
```

**Comment by eistrati** [comment] 2020-04-10 14:18
@willarmiros thank you! any thoughts and/or timelines on when `mysql2` will be supported? as of today, it looks much more performant than `mysql` one. we'll try it with my team and see if the workaround solves our current needs (at least temporarily). thanks again! your input is very much appreciated.

**Comment by willarmiros** [comment] 2020-04-10 15:05
Unfortunately we cannot provide timelines for future features. It is in our backlog however and I will update this issue once it gets prioritized.

**Comment by willarmiros** [comment] 2020-04-10 15:54
Apologies! I did not realize that there was in fact an issue already open to support `mysql2` and we do indeed provide partial support for it! In #6 some other customers appear to have implemented partial support for `mysql2`, particularly the `query()` and `execute()` methods. Note that you'll need to have `3.0.0-alpha.2` installed to support `async/await` capturing.

Although there appear to be some issues with `pool.execute()`. Furthermore, this support & caveats for `mysql2` should be documented, which I'll add shortly. The following *should* provide the partial support described in #6: 

```js
var mysql2 = AWSXRay.captureMySQL(require('mysql2'));
```

 I'll be closing this as a duplicate of #6 (and #271 for sequelize). Please follow up over there with any issues you experience.

**Closed by willarmiros** 2020-04-10 15:54 UTC
Labels: enhancement
