### ISSUE TITLE
Allow disabling SDK with AWS_XRAY_SDK_DISABLED

### ISSUE THREAD

**Issue by anuraaga** [aws/aws-xray-sdk-node#331] opened 2020-09-08 07:30 UTC
We have an environment variable for disabling the SDK in other languages but don't have it yet for node from what I can tell.

**Comment by willarmiros** [comment] 2020-09-08 21:30
Closing as duplicate of #231. This is near the top of our backlog though and we hope to close it out as soon as possible.

**Closed by willarmiros** 2020-09-08 21:30 UTC
