### ISSUE TITLE
aws-xray-sdk-core bloats package bundles

### ISSUE THREAD

**Issue by compwright** [aws/aws-xray-sdk-node#54] opened 2018-09-21 17:54 UTC
When deploying on AWS Lambda, `aws-sdk` does not need to be bundled since it is already present in the Node.js runtime. This yields significant bundle savings, but... not if you're using `aws-xray-sdk-core`.

The reason for this is `aws-xray-sdk-core` requires `aws-sdk` as a normal dependency. It should be a `peerDependency` and possibly a `devDependency`.

**Comment by awssandra** [comment] 2018-11-29 00:20
Since the issue is the bundled size of the SDK now addressed in [PR 73](https://github.com/aws/aws-xray-sdk-node/pull/73) I will close this issue unless there are any further concerns.

Thanks!

**Closed by awssandra** 2018-11-29 00:20 UTC
Labels: enhancement

**Comment by johnbradleyCs** [comment] 2018-11-29 10:57
@awssandra I don't believe that PR 73 resolves this issue - the node_modules folder will still contain the aws-sdk + all depedencies after 'npm install'.
Unless I'm missing something obvious (I might be...) add something like the suggested https://github.com/serverless-heaven/serverless-webpack as suggested in the comment in  #https://github.com/aws/aws-xray-sdk-node/pull/55 to remove the aws-sdk
