### ISSUE TITLE
'captureAWSv3Client' cannot be used as a value because it was exported using 'export type'

### ISSUE THREAD

**Issue by aaroncowie** [aws/aws-xray-sdk-node#395] opened 2021-03-29 02:31 UTC
Just trying out the new AWS JS SDK v3 compatibility with typescript and we noticed that this line in aws-xray.d.ts appears to only export the type for captureAWSv3Client but not the function alias itself.

The error we get is:
` error TS1362: 'captureAWSv3Client' cannot be used as a value because it was exported using 'export type'`

If I am correct, it seems as though
`export type { captureAWSClient as captureAWSv3Client } from './patchers/aws3_p';`
just needs to be changed to
`export { captureAWSClient as captureAWSv3Client } from './patchers/aws3_p';`

https://github.com/aws/aws-xray-sdk-node/blob/5ead789162b370c069e7cf5c1e483fbb257a95c6/packages/core/lib/aws-xray.d.ts#L42

**Comment by willarmiros** [comment] 2021-04-06 00:36
Hi @aaroncowie,

This change has not been released to NPM yet, so you cannot use the `captureAWSv3Client` API (unless you are building the repo from source). I'll close this as a duplicate of #294, it will be available with the next release of this SDK.

**Comment by willarmiros** [comment] 2021-04-13 03:06
@aaroncowie I believe I closed this issue prematurely, and the `export type` issue still exists as you initially stated. Sorry for the eager close, I'll reopen until this is fixed.

**Comment by jwoehrle** [comment] 2021-05-14 14:20
this seems to be fixed with v3.3.3

**Comment by willarmiros** [comment] 2021-05-14 14:48
That's right @jwoehrle, I'll go ahead and close this out.

**Closed by willarmiros** 2021-05-14 14:48 UTC
