### ISSUE TITLE
3.0.0-alpha.2 - attempting to fetch sampling rules crashes application when agent is not running

### ISSUE THREAD

**Issue by pdhodgkinson** [aws/aws-xray-sdk-node#267] opened 2020-03-26 13:39 UTC
We've just upgraded our application from alpha.1 to alpha.2 for testing and immediately noticed that the application exited in cases where the xRay agent was not running on the configured url:port.
This was not the behaviour in alpha.1

The application is an express server, and we are using the `express_mw` module, and using `AWSXRay.captureHTTPsGlobal`.

I did some digging and found the difference appears to be somewhere in the hierarchy that starts with `mwUtils.resolveSampling(amznTraceHeader, segment, res);`
https://github.com/aws/aws-xray-sdk-node/blob/aws-xray-sdk%403.0.0-alpha.2/packages/express/lib/express_mw.js#L40
and proceeds down to `service_connector.js:fetchSamplingRules`
https://github.com/aws/aws-xray-sdk-node/blob/aws-xray-sdk%403.0.0-alpha.2/packages/core/lib/middleware/sampling/service_connector.js#L23

Here there appears to be some custom http request handling, that, when there is no agent running, or it's running on a different port,  throws an `ECONNREFUSED` error like
`
  trace: [
    {
      column: 16,
      file: 'net.js',
      function: 'TCPConnectWrap.afterConnect [as oncomplete]',
      line: 1134,
      method: 'afterConnect [as oncomplete]',
      native: false
    }
  ],
  stack: [
    'Error: connect ECONNREFUSED 127.0.0.1:2000',
    '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)'
  ]`
This does not get caught anywhere in the stack, and results in a runtime `uncaughtException` that terminates the application. It seems to sidestep any express error capturing logic I put in.

In `alpha.1` it appears that fetchSamplingRules was implemented using a completely different http client (the AWS-SDK request library?), and for some reason that seems to have swallowed and hidden any ECONNREFUSED errors.
https://github.com/aws/aws-xray-sdk-node/blob/aws-xray-sdk%403.0.0-alpha.1/packages/core/lib/middleware/sampling/service_connector.js#L22

An ideal fix (for us) would be to capture and log any errors connecting (or using) the agent to the logger and not crash the application. Or possibly make the error behaviour configurable? Note that we are already using the ` AWSXRay.setContextMissingStrategy` to avoid the RUNTIME_ERROR cases for missing context.

**Comment by willarmiros** [comment] 2020-03-26 14:16
Hi @pdhodgkinson ,
Thank you very much for raising this issue. Did you configure the different address of the daemon via the `AWS_XRAY_DAEMON_ADDRESS` environment variable? I'll try to reproduce this error on my end and resolve it (since it shouldn't be happening in the first place). Generally though you are correct that X-Ray, as a tool purely for observability, should not be causing runtime errors in your main application. I'll improve the error capturing as well.

For some context, we changed the way the sampling APIs were called from using the AWS SDK to the native HTTP client to eliminate our dependency on the AWS SDK package.

**Comment by pdhodgkinson** [comment] 2020-03-26 15:55
We are using the `setDaemonAddress` function, but not the ENVIRONMENT variable
Our boilerplate looks something like:
`
  const AWSXRay = require('aws-xray-sdk');
    const address = `${host}:${port}`;
    AWSXRay.setDaemonAddress(address);
  AWSXRay.config([AWSXRay.plugins.ECSPlugin]);
 AWSXRay.captureHTTPsGlobal(require('https'), true);
    AWSXRay.captureHTTPsGlobal(require('http'), true);
AWSXRay.setContextMissingStrategy((...args) => {
       ...
    });
AWSXRay.captureAWS(require('aws-sdk'));
`

**Comment by willarmiros** [comment] 2020-03-26 17:14
Yep, that setup looks correct. I've reproduced the error and caught it so it shouldn't disrupt your application anymore, and verified that it works with a non-default address. I'll get the PR for that out later today.

Do you think the reason it wasn't initially connecting was just some delayed start in the daemon?

**Comment by pdhodgkinson** [comment] 2020-03-26 18:54
It's mostly when our developers are running the application locally during development. They don't typically run the agent so there's nothing running on that port. Have not had this issue in a production environment

**Comment by willarmiros** [comment] 2020-03-26 21:36
^ PR is out, we'll try to release it next week!

**Comment by pdhodgkinson** [comment] 2020-03-28 00:59
Thanks! The PR looks to have fixed the issue for us. 🍻

**Comment by willarmiros** [comment] 2020-04-21 21:58
Fix released in 3.0.0 :)

**Closed by willarmiros** 2020-04-21 21:58 UTC
Labels: bug
