### ISSUE TITLE
captureAWSv3Client doesn't work with LambdaClient

### ISSUE THREAD

**Issue by paul-uz** [aws/aws-xray-sdk-node#505] opened 2022-05-04 08:47 UTC
`captureAWSv3Client` is not compatible with the v3 LambdaClient

<img width="702" alt="Screenshot 2022-05-04 at 09 45 46" src="https://user-images.githubusercontent.com/73826774/166649517-d966beb1-f190-49c6-ad6c-5a9ff9a40d3d.png">

Error below:

```
Argument of type 'LambdaClient' is not assignable to parameter of type 'Client<any, any, any>'.
  The types of 'middlewareStack.concat' are incompatible between these types.
    Type '<InputType extends ServiceInputTypes, OutputType extends ServiceOutputTypes>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<...>' is not assignable to type '<InputType extends any, OutputType extends any>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<InputType, OutputType>'.
      Types of parameters 'from' and 'from' are incompatible.
        Type 'MiddlewareStack<InputType, OutputType>' is not assignable to type 'MiddlewareStack<InputType, ServiceOutputTypes>'.
          Types of property 'addRelativeTo' are incompatible.
            Type '(middleware: MiddlewareType<InputType, OutputType>, options: RelativeMiddlewareOptions) => void' is not assignable to type '(middleware: MiddlewareType<InputType, ServiceOutputTypes>, options: RelativeMiddlewareOptions) => void'.
              Types of parameters 'middleware' and 'middleware' are incompatible.
                Type 'MiddlewareType<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                  Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                    Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'InitializeMiddleware<InputType, OutputType>'.
                      Call signature return types 'InitializeHandler<InputType, ServiceOutputTypes>' and 'InitializeHandler<InputType, OutputType>' are incompatible.
                        Type 'Promise<InitializeHandlerOutput<ServiceOutputTypes>>' is not assignable to type 'Promise<InitializeHandlerOutput<OutputType>>'.
                          Type 'InitializeHandlerOutput<ServiceOutputTypes>' is not assignable to type 'InitializeHandlerOutput<OutputType>'.
                            Types of property 'output' are incompatible.
                              Type 'ServiceOutputTypes' is not assignable to type 'OutputType'.
                                'ServiceOutputTypes' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'any'.
                                  Type 'AddLayerVersionPermissionCommandOutput' is not assignable to type 'OutputType'.
                                    'AddLayerVersionPermissionCommandOutput' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'any'.ts(2345)
```

**Comment by paul-uz** [comment] 2022-05-04 08:57
Looks like compatibility broke going from v3 SDK 3.51.0 to 3.82.0 🤦 In the screenshot, client-dynamodb is 3.51.0 and client-lambda is 3.82.0. Updating client-dynamodb to 3.82.0 and it also errors.

**Comment by willarmiros** [comment] 2022-05-16 22:24
Hi @paul-uz, thanks for raising this. We've seen similar issues in the past, the workaround for now is to case the client type as `any` in the instrumentation statement: https://github.com/aws/aws-xray-sdk-node/tree/master/packages/core#capture-outgoing-aws-requests-on-a-single-client

#449 should address this but we need to think further on its impact. I'm going to close this as a duplicate of #439 for now, but we will prioritize the PR when we can to no longer require the workaround

**Closed by willarmiros** 2022-05-16 22:24 UTC
